-- ============================================================
-- DYNOBOO FINANCIAL REPORT MODULE
-- Migration 006: Laporan Finansial (Cashflow)
-- ============================================================

-- ── Kategori Finansial ───────────────────────────────────────
CREATE TABLE IF NOT EXISTS financial_categories (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nama        TEXT NOT NULL,
    tipe        TEXT NOT NULL CHECK (tipe IN ('PEMASUKAN', 'PENGELUARAN')),
    warna       TEXT NOT NULL DEFAULT '#38bdf8',
    created_at  TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE financial_categories DISABLE ROW LEVEL SECURITY;


-- Seed kategori default Pemasukan
INSERT INTO financial_categories (nama, tipe, warna) VALUES
  ('Penjualan Produk',  'PEMASUKAN',   '#10b981'),
  ('Workshop',          'PEMASUKAN',   '#34d399'),
  ('Investasi',         'PEMASUKAN',   '#06b6d4'),
  ('Lain-lain',         'PEMASUKAN',   '#38bdf8');

-- Seed kategori default Pengeluaran
INSERT INTO financial_categories (nama, tipe, warna) VALUES
  ('Bahan Baku',        'PENGELUARAN', '#f59e0b'),
  ('Operasional',       'PENGELUARAN', '#ef4444'),
  ('Pemasaran',         'PENGELUARAN', '#a78bfa'),
  ('Gaji / Honor',      'PENGELUARAN', '#fb7185'),
  ('Lain-lain',         'PENGELUARAN', '#6b7280');


-- ── Transaksi Finansial ──────────────────────────────────────
CREATE TABLE IF NOT EXISTS financial_transactions (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tipe          TEXT NOT NULL CHECK (tipe IN ('PEMASUKAN', 'PENGELUARAN')),
    kategori_id   BIGINT REFERENCES financial_categories(id) ON DELETE SET NULL,
    nominal       NUMERIC(18,2) NOT NULL DEFAULT 0,
    detail        TEXT,           -- Detail singkat pengeluaran/pemasukan
    deskripsi     TEXT,           -- Catatan/note panjang
    tanggal       DATE NOT NULL DEFAULT CURRENT_DATE,
    created_by    TEXT NOT NULL DEFAULT 'superadmin',
    created_at    TIMESTAMPTZ DEFAULT NOW(),
    updated_at    TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE financial_transactions DISABLE ROW LEVEL SECURITY;

